package com.hamurcuabi.core_ui

object Strings {
    const val gainWeight = "Gain"
    const val loseWeight = "Lose"
    const val keepWeight = "Keep"
    const val height = "cm"
    const val weight = "kg"
    const val error_unknown = "Unknown error"
    const val welcome_text = "Hello! Let\'s find out more about you :)"
    const val lets_go = "Let\'s go"
    const val whats_your_gender = "What is your gender?"
    const val male = "Male"
    const val female = "Female"
    const val whats_your_age = "What\'s your age?"
    const val next = "Next"
    const val whats_your_height = "What\'s your height?"
    const val kg = "kg"
    const val cm = "cm"
    const val error_age_cant_be_empty = "The age can\'t be empty"
    const val error_height_cant_be_empty = "The height can\'t be empty"
    const val error_weight_cant_be_empty = "The weight can\'t be empty"
    const val kcal = "kcal"
    const val carbs = "Carbs"
    const val protein = "Protein"
    const val fat = "Fat"
    const val previous_day = "Previous day"
    const val next_day = "Next day"
    const val yesterday = "Yesterday"
    const val tomorrow = "Tomorrow"
    const val nutrient_info = "%dg • %dkcal"
    const val amount_info = "%dg"
    const val grams = "g"
    const val extend = "Extend"
    const val collapse = "Collapse"
    const val breakfast = "Breakfast"
    const val lunch = "Lunch"
    const val dinner = "Dinner"
    const val snacks = "Snacks"
    const val add_meal = "Add %s"
    const val add = "Add"
    const val search = "Search..."
    const val today = "Today"
    const val recent = "Recent"
    const val kcal_per_100g = "%dkcal / 100g"
    const val track = "Track"
    const val error_something_went_wrong = "Oops, something went wrong!"
    const val no_results = "No results"
    const val error_invalid_values = "These are not valid values"
    const val what_are_your_nutrient_goals = "What are your nutrient goals?"
    const val percent_proteins = "% proteins"
    const val percent_fats = "% fats"
    const val percent_carbs = "% carbs"
    const val high = "High"
    const val medium = "Medium"
    const val years = "years"
    const val whats_your_weight = "What\'s your weight?"
    const val low = "Low"
    const val gain = "Gain"
    const val keep = "Keep"
    const val lose = "Lose"
    const val lose_keep_or_gain_weight = "Do you want to lose, keep or gain weight?"
    const val whats_your_activity_level = "What\'s your activity level?"
    const val error_not_100_percent = "The values must add up to 100%"
    const val your_goal = "Your goal:"
    const val delete = "Delete"

}
    

